### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mef** [mef/linux-mef#1]
- [x] Firefox setup: remove ESR, install stable + developer edition
- [ ] Firefox config: add userChrome and userContent files
- [x] chromium install
- [x] Inkscape install
- [ ] virtual machines setup
- [ ] customizations: conky, tint2, openbox, theme, xdg-user-dirs (un-capitalize directory names)
- [x] unattended-upgrades + suitable alerting
